# -*- coding: utf-8 -*-
{
    'name': 'HiTech AFAFERP Invoice Format Editor',
    'version': '18.0.1.0.0',
    'category': 'Accounting',
    'summary': 'Invoice Report, Report Editor, Customise Invoice Report, '
               'Invoice Report Templates, Account Reports, Odoo18, '
               'Odoo Apps, Report Templates, Odoo18, Odoo Apps',
    'description': """Invoice Format Editor For Configuring the Invoice Templates""",
    'author': 'HiTechnologia',
    'depends': ['account', 'web', 'sale_management'],
    'data': ['security/ir.model.access.csv',
             'data/design_templates.xml',
             'data/normal_preview_templates.xml',
             'data/modern_preview_templates.xml',
             'data/old_standard_preview_templates.xml',
             'views/doc_layout_views.xml',
             'views/base_document_layout_views.xml',
             'views/custom_external_layout_templates.xml',
             'reports/normal_invoice_templates.xml',
             'reports/modern_invoice_templates.xml',
             'reports/old_standard_invoice_templates.xml',
             'reports/report_invoice_templates.xml',
             'reports/preview_layout_report_templates.xml',
             ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
