{
    'name': ' HiTech AFAFERP Base Usability',
    'version': '18.0',
    'category': 'Partner',
    'license': 'AGPL-3',
    'summary': 'Better usability in base module',
    'author': 'HiTechnologia',
    'depends': ['base'],
    'data': [
        'security/group.xml',
        'security/ir.model.access.csv',
        'views/res_partner.xml',
        'views/res_partner_bank.xml',
        'views/res_country.xml',
        'views/res_company.xml',
        'views/ir_config_parameter.xml',
        'views/ir_module.xml',
        'views/ir_sequence.xml',
        ],
    'installable': True,
}
